### ISSUE TITLE
Hard to read roadmap

### ISSUE THREAD

**Issue by WebReflection** [ValeLang/Vale#485]
I am partially color blinded and beside the "*planned*" round image I really have [hard time to quickly understand the current state of a feature, if it's done or in progress](https://vale.dev/roadmap).

How about using something as simple and easy to both eyes and bandwidth as input radio are?

Try this on any browser, as example:
```js
document.body.innerHTML = `
<style>label {display:block}</style>
<label><input type=radio checked> Done</label>
<label><input type=radio checked disabled> In progress</label>
<label><input type=radio disabled> To do</label>
`;
```

it's perfectly visible without needing images at all, and it's super clear what's going on.

Thanks in advance for considering improvements in the Vale website 👋

**Comment by Verdagon** [comment]
Thanks for reporting this! I did a colorblindness overhaul for the site a year or so back, and it seems I missed this aspect.

I've pushed an update to the site, where we use black and white icons, and colored text. Let me know if the colors are too light, sometimes I make that mistake.

I also used the opportunity to improve the page in general with more content!

**Comment by WebReflection** [comment]
@Verdagon definitively an improvement, at least icon speaking, but to me the contrast/difference between done and in progress is still not excellent. Anyway, thanks!

![Screenshot from 2022-04-25 18-57-39](https://user-images.githubusercontent.com/85749/165137348-85852ed4-7379-4fb9-9ece-a43a89c28330.png)

**Comment by Verdagon** [comment]
Good catch, I'd forgotten about the red vs. green aspect. I changed in-progress to blue, does that help at all? Thanks!

**Comment by WebReflection** [comment]
Waaaay better 👍
